apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Cluster infrastructure (cert-manager, Envoy Gateway, Gateway API edge, ClusterIssuers)
  sourceRepos:
    - https://charts.jetstack.io
    - docker.io/envoyproxy/gateway-crds-helm
    - docker.io/envoyproxy/gateway-helm
    - https://github.com/humble92/argo-examples.git
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: envoy-gateway-system
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: gateway.networking.k8s.io
      kind: GatewayClass
    - group: cert-manager.io
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
