apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
